"""initial schema

Revision ID: ec16fa0f0980
Revises: 
Create Date: 2026-09-18 18:54:00.070019

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec16fa0f0980'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_code', sa.String(length=12), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('access_token_signed', sa.String(length=255), nullable=True),
    sa.Column('owner_token_hash', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('guest_upload_enabled', sa.Boolean(), nullable=False),
    sa.Column('guest_download_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('access_token_hash', name=op.f('uq_rooms_access_token_hash')),
    sa.UniqueConstraint('owner_token_hash', name=op.f('uq_rooms_owner_token_hash'))
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_room_code'), ['room_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_audit_events_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_room_id'), ['room_id'], unique=False)

    op.create_table('sessions',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_sessions_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_sessions_session_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_room_id'), ['room_id'], unique=False)

    op.create_table('files',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_files_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sessions.id'], name=op.f('fk_files_uploaded_by_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_files_storage_key'))
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_session_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_messages_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_session_id'], ['sessions.id'], name=op.f('fk_messages_sender_session_id_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))

    op.drop_table('messages')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index(batch_op.f('ix_files_room_id'))

    op.drop_table('files')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_room_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_room_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_status'))
        batch_op.drop_index(batch_op.f('ix_rooms_room_code'))
        batch_op.drop_index(batch_op.f('ix_rooms_expires_at'))

    op.drop_table('rooms')
    # ### end Alembic commands ###
